import { chromium } from '@playwright/test';
const BASE='http://127.0.0.1:8770';
const b=await chromium.launch({channel:'chromium-headless-shell'}).catch(()=>chromium.launch());
const p=await b.newPage({viewport:{width:1280,height:900}});
const json=await (await p.request.get(BASE+'/portfolio-data.json')).text();
await p.goto(BASE+'/index.html');
await p.evaluate(d=>{localStorage.setItem('portfolio-command-centre-data',d);localStorage.setItem('portfolio-command-centre-meta',JSON.stringify({savedAt:new Date().toISOString(),projectCount:JSON.parse(d).projects.length}));localStorage.setItem('pcc-theme','dark');},json);
await p.reload();
const r=await p.$('#restoreBanner button.btn-primary'); if(r) await r.click();
await p.waitForSelector('#projectTableBody tr',{timeout:8000});
await p.evaluate(()=>{App.setActiveCustomer('Acme Industries');App.navigate('capacity');});
await p.waitForTimeout(500);
await p.screenshot({path:'dist/shots/dark-capacity.png'});
await p.evaluate(()=>{App.navigate('dashboard');});
await p.waitForTimeout(400);
await p.evaluate(()=>{const id=App.data.projects[0].id;DetailPanel.open(id);});
await p.waitForTimeout(500);
await p.screenshot({path:'dist/shots/dark-detail.png'});
await b.close();
